apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: psav-test
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/psav/docs-test/
spec:
  type: service
  lifecycle: production
  owner: psavage
